[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip STM32F072RBT6 --verify --no-location"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "linker=flip-link",
]

[build]
target = "thumbv6m-none-eabi"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
